add_newline = false
format = "$directory$git_branch$git_status$character"

[directory]
style = "bold blue"
truncation_length = 3
truncation_symbol = "â€¦/"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[<](bold red)"

